const fs = require('fs');
const path = require('path');

// Read the HTML, JS, and CSS files
const htmlContent = fs.readFileSync(path.join(__dirname, 'public', 'index.html'), 'utf8');
const jsContent = fs.readFileSync(path.join(__dirname, 'public', 'app.js'), 'utf8');
const cssContent = fs.readFileSync(path.join(__dirname, 'public', 'styles.css'), 'utf8');

// Create the worker file with embedded content
const workerContent = `// This file is auto-generated by build.js
const HTML_CONTENT = ${JSON.stringify(htmlContent)};
const JS_CONTENT = ${JSON.stringify(jsContent)};
const CSS_CONTENT = ${JSON.stringify(cssContent)};

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // Serve the HTML page
    if (url.pathname === '/' || url.pathname === '/index.html') {
      return new Response(HTML_CONTENT, {
        headers: {
          'Content-Type': 'text/html;charset=UTF-8',
        },
      });
    }

    // Serve the JavaScript file
    if (url.pathname === '/app.js') {
      return new Response(JS_CONTENT, {
        headers: {
          'Content-Type': 'application/javascript',
        },
      });
    }

    // Serve the CSS file
    if (url.pathname === '/styles.css') {
      return new Response(CSS_CONTENT, {
        headers: {
          'Content-Type': 'text/css;charset=UTF-8',
        },
      });
    }

    return new Response('Not Found', { status: 404 });
  },
};
`;

// Write the built worker file
fs.writeFileSync(path.join(__dirname, 'src', 'index.js'), workerContent);
console.log('Build complete! Generated src/index.js');
